name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  change_detection:
    runs-on: ubuntu-latest
    outputs:
      service1: ${{ steps.filter.outputs.service1 }}
      service2: ${{ steps.filter.outputs.service2 }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            service1:
              - 'code1/**'
            service2:
              - 'code2/**'
              
  service1:
    name: Service1
    needs: change_detection
    if: ${{ needs.change_detection.outputs.service1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./code1/requirements.txt
      
      - name: Test with pytest
        run: |
          pip install pytest-cov
          cd code1/
          python -m pytest --cov=.
        
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ steps.time.outputs.time }}-$GITHUB_RUN_NUMBER
          COVERALLS_PARALLEL: true
          
          
  service2:
    name: Service2
    needs: change_detection
    if: ${{ needs.change_detection.outputs.service2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./code2/requirements.txt
      
      - name: Test with pytest
        run: |
          pip install pytest-cov
          cd code2/
          python -m pytest --cov=.
        
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ steps.time.outputs.time }}-$GITHUB_RUN_NUMBER
          COVERALLS_PARALLEL: true
  
  finish:
    needs: change_detection
    if: ${{ needs.change_detection.outputs == 'true'}}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
